### ISSUE TITLE
OAuth2 authentification fails, configuration can not be completed

### ISSUE THREAD

**Issue by frantsch** [owncloud/files_external_dropbox#18]
**Steps to reproduce**

> 

     1. Create a Dropbox-App, indicating my Redirect URI and obtaining my App Key and App Secret for OAuth2 (following README.md on https://github.com/owncloud/files_external_dropbox/) 
     2. Recieving a eMail-Message whereafter I successfully linked my owncloud domain with dropbox
     3. Installing the new Owncloud App "External Storage: Dropbox" (V1.0.0) into my owncloud instance
     4. Calling Owncloud Settings - External Storage - Dropbox
     5. Try to add storage type Dropbox, enter Directory Name, my App Key and App Secret for OAuth2, and Users, and click to permit access

    
**Expected behaviour**

     Integration of Dropbox Storage is established, a green mark shows up for the storage configuration

**Actual behaviour**

     The mark of the storage configuration becomes red as well as the two configuration fields (Client-ID, App-Secret), integration fo Dropbox Storage fails, although I am sure to use the correct Key and Secret

**Server configuration**

Operating system:
     Linux

Web server:
     Apache

Database:
     SQLite

PHP version:
     5.6

ownCloud version: (see ownCloud admin page)
     10.0.3.3

Updated from an older ownCloud or fresh install:
     fresh

Where did you install ownCloud from:
     Download from owncloud.org

**Comment by frantsch** [comment]
Sorry, I just realized that an issue on this is already existing:
https://github.com/owncloud/files_external_dropbox/issues/13

**Comment by PVince81** [comment]
@frantsch ok, now I see that the fix for #13 should be https://github.com/owncloud/core/issues/29225 which will be released in 10.0.4. Currently 10.0.4 is in RC1. You could either try with that version or patch your core with https://github.com/owncloud/core/issues/29225.patch

**Comment by patrickjahns** [comment]
@frantsch 
Could you try using the master branch from files_external_owncloud together with RC1 or the patch from vincent and see if this is still occuring

**Comment by bcutter** [comment]
Wow that´s quite tough. I´m strongly interested in how to solve this. Followed I think three or four references to get here. Anything I can test or contribute?

**Comment by Hemant-Mann** [comment]
I think this should be fixed in v1.0.1 @patrickjahns ?

**Comment by bcutter** [comment]
Updated to OC v10.0.6.1 today. Still not working, even they claimed to remove the old Dropbox module support (even worse the new one still doesn´t work).

**Comment by patrickjahns** [comment]
@bcutter 
Please give some more insight - have you used the app from the marketplace or the pending release from source?

**Comment by bcutter** [comment]
@patrickjahns: Marketplace.

**Comment by patrickjahns** [comment]
@bcutter 
There is a pending release - with fixes included - please try it 

Note - a known issue is #27 - we will move forward with releasing the minor fixes until it can be resolved

**Comment by patrickjahns** [comment]
@bcutter 
1.0.1 version is released on marketplace, issue should be resolved

**Comment by bcutter** [comment]
I can confirm the bug is **finally** fixed (using 1.0.1 from marketplace).
